services:
  db:
    image: ghcr.io/axeltlarsson/receptdatabasen-db:latest
    restart: unless-stopped
    networks:
      - net
    environment:
      # env vars specific to postgres image used on first boot
      - POSTGRES_USER=${SUPER_USER}
      - POSTGRES_PASSWORD=${SUPER_USER_PASSWORD}
      - POSTGRES_DB=app
      # env vars useful for our sql scripts
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - DB_NAME=app
      - DB_USER=authenticator
      - DB_PASS=${DB_PASS}
      - DB_ANON_ROLE=anonymous
      - DEVELOPMENT=1
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=2592060
      - PG_VERSION=12
      - RP_ID=${RP_ID}
      - ORIGIN=${ORIGIN}
      - DISABLE_USER_VERIFICATION=false

    volumes:
      - db-vol:/var/lib/postgresql/data

  # PostgREST instance, is responsible for communicating with the database
  # and providing a REST api, (almost) every request that is sent to the database goes through it
  postgrest:
    image: postgrest/postgrest:v12.0.2
    restart: unless-stopped
    environment:
      - PGRST_DB_URI=postgres://authenticator:${DB_PASS}@db:5432/app
      - PGRST_DB_SCHEMA=api
      - PGRST_DB_ANON_ROLE=anonymous
      - PGRST_DB_POOL=10
      - PGRST_JWT_SECRET=${JWT_SECRET}
      - PGRST_MAX_ROWS=5000
    depends_on:
      - db
    networks:
      - net

  # OpenResty (Nginx + Lua) instance that sits in front of PostgREST.
  # All the requests coming into the system are first hitting this component.
  # After some processing/checks and transformation, the request is forwarded
  # to PostgREST down the stack.
  openresty:
    image: ghcr.io/axeltlarsson/receptdatabasen-openresty:latest
    command: ["/usr/bin/openresty", "-g", "daemon off; error_log /dev/stderr info;"]
    environment:
      - DEVELOPMENT=1
      - POSTGREST_HOST=postgrest
      - POSTGREST_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
      - DB_SCHEMA=api
      - DB_USER=authenticator
      - DB_PASS=${DB_PASS}
      - COOKIE_SESSION_SECRET=${COOKIE_SESSION_SECRET}
        # cookie should expire before jwt: 30 days;
      - COOKIE_SESSION_LIFETIME=2592000
    volumes:
      - uploads-vol:/uploads
    depends_on:
      - postgrest
    networks:
      - net
    ports:
      - "${OPENRESTY_PORT}:80"

volumes:
  db-vol:
  uploads-vol:

networks:
  net:
