version: '3'
services:
  server:
    image: postgrest/postgrest:v6.0.2
    ports:
      - "3000:3000"
    networks:
      - backend-net
    environment:
      PGRST_DB_URI: postgres://api_user:password@db:5432/recipe_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_user #In production this role should not be the same as the one used for the connection
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    networks:
      - backend-net
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./db_scripts/:/docker-entrypoint-initdb.d
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
networks:
  backend-net:

volumes:
  db-volume:
