# Production environment docker-compose setup
#
version: '3.7'
services:
  db:
    restart: unless-stopped
    build:
      context: ./db
      args:
        - VERSION=${PG_VERSION}

  postgrest:
    restart: unless-stopped

  openresty:
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - webproxy

networks:
  webproxy:
    external: true
    name: ${PROXY_NETWORK}
