# Production environment docker-compose setup
#
version: '3.7'
services:
  db:
    restart: unless-stopped
    build:
      context: ./db
      args:
        - VERSION=${PG_VERSION}

  postgrest:
    restart: unless-stopped

  openresty:
    restart: unless-stopped

# networks:
  # backend:
  # frontend:


# Used in production
# It adds the app and db to a new isolated network: backend

# version: '3'

# services:
  # app:
    # environment:
      # DB_URL: "jdbc:postgresql://db:5432/listan"
    # restart: unless-stopped
    # networks:
      # - backend
      # - frontend
  # frontend:
    # environment:
      # VIRTUAL_HOST: "${VIRTUAL_HOST}"
      # LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
      # LETSENCRYPT_EMAIL: "${EMAIL}"
    # restart: unless-stopped
    # networks:
      # - frontend
  # db:
    # environment:
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
    # restart: unless-stopped
    # volumes:
      # - db-volume:/var/lib/postgresql/data
    # networks:
      # - backend

# volumes:
  # db-volume:
# networks:
  # backend:
  # frontend:

