name: Build and Push Docker Images

on:
  push:
    branches:
      - axel/nixos
    paths:
      - 'frontend/**'
      - 'openresty/**'
      - 'db/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push db
      uses: docker/build-push-action@v5
      with:
        context: ./db
        build-args: |
          PG_VERSION=12
        file: ./db/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:latest
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

    # TODO: https://docs.docker.com/build/ci/github-actions/share-image-jobs/
    # instead of pushing to registry, as this image is fairly useless on its own
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-frontend:latest
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-frontend:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

    - name: Build and push openresty
      uses: docker/build-push-action@v5
      with:
        context: ./openresty
        file: ./openresty/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-openresty:latest
          ghcr.io/${{ github.repository_owner }}/receptdatabasen-openresty:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
