name: Build and Push Docker Images

on:
  push:
    branches:
      - axel/nixos
    paths:
      - 'frontend/**'
      - 'openresty/**'
      - 'db/**'

jobs:

  build-and-push-db:
    if: contains(github.event.push.commits[].modified, 'db/')
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image for db
        uses: ./.github/actions/docker-build-push
        with:
          context: ./db
          dockerfile: ./db/Dockerfile
          tags: >
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:latest,
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:${{ github.sha }}
          build-args: PG_VERSION=12
          cache-ref: ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:cache

  build-frontend:
    if: contains(github.event.push.commits[].modified, 'frontend/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image for frontend (no push)
        uses: ./.github/actions/docker-build-push
        with:
          context: ./frontend
          dockerfile: ./frontend/Dockerfile
          tags: frontend:build
          cache-ref: ghcr.io/${{ github.repository_owner }}/receptdatabasen-frontend:cache
          push: 'false'

  build-and-push-openresty:
    needs: build-frontend
    if: contains(github.event.push.commits[].modified, 'openresty/')
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image for openresty
        uses: ./.github/actions/docker-build-push
        with:
          context: ./openresty
          dockerfile: ./openresty/Dockerfile
          tags: >
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-openresty:latest,
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-openresty:${{ github.sha }}
          build-args: FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/receptdatabasen-frontend:latest
          cache-ref: ghcr.io/${{ github.repository_owner }}/receptdatabasen-openresty:cache
