name: Build and push db Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'db/**'

jobs:

  build-and-push-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push db
        uses: docker/build-push-action@v5
        with:
          context: ./db
          build-args: |
            PG_VERSION=12
          file: ./db/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:latest
            ghcr.io/${{ github.repository_owner }}/receptdatabasen-db:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
